version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "@types/node"
    version_requirement_updates: "increase_versions"
